### ISSUE TITLE
Fails (silently) if deb package uses zstd

### ISSUE THREAD

**Issue by sevens** [vborrego/deb2tgz#1]
Using `deb2tgz` on a Debian package that uses zstd for its internal compression (e.g. `data.tar.zst`) fails silently: no Slackware package is created and no output is generated.

To reproduce:
* Download a Debian package that uses zst (any package for a recent Ubuntu release should do, e.g. https://packages.ubuntu.com/jammy/amd64/less/download )
* Try to convert it using `deb2tgz`
* Observe that no Slackware package is created

**Comment by sevens** [comment]
I've added a quick fix ( https://github.com/sevens/deb2tgz/commit/9a990965577c286a268ac982172cc502564c155f and https://github.com/sevens/deb2tgz/commit/9829fbf1309439b96dfa9f93a79c486491daabbf ), can create a pull request for it if you want.

**Comment by vborrego** [comment]
Hi @sevens . Made a correction based on your suggested commits regarding zst.

**Comment by sevens** [comment]
Nice, thanks :)

FYI: I also made 2 other small changes/improvements which might be useful:
*  Exit with error on unsupported compression formats (https://github.com/sevens/deb2tgz/commit/a0313ae75cee463970eb30c22bc8cf8080f643ae), should make it much easier to debug/troubleshoot similar problems in the future
* Output error messages to `stderr` (https://github.com/sevens/deb2tgz/commit/3d9cab15eddb372fccceb65f2e0a6993e8d156df)

Let me know if a pull request for any of these is desired.
